name: todoapp
description: A new Flutter project.
homepage: https://primeholding.com
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.22.2 <4.0.0'

dependencies:
  alice: ^0.4.1
  alice_dio: ^1.0.4
  collection: ^1.18.0
  connectivity_plus: ^6.0.5
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: 7.0.0
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.7
  http: ^1.2.2
  jaguar_jwt: ^3.0.0
  json_annotation: ^4.9.0
  jwt_decoder: ^2.0.1
  provider: ^6.1.2
  realm: ^20.0.0
  retrofit: ^4.4.1
  rx_bloc: ^6.0.0
  rx_bloc_list: ^5.0.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  uuid: ^4.5.0
  widget_toolkit: ^0.2.0

dev_dependencies:
  alchemist: ^0.11.0
  build_runner: ^2.4.12
  clean_coverage: ^0.0.3
  copy_with_extension_gen: ^5.0.4
  flutter_lints: any
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  patrol: ^3.11.2 
  r_flutter: 0.9.0
  retrofit_generator: ^8.2.1
  rx_bloc_generator: ^8.0.0
  rx_bloc_test: ^5.0.0
  test: any

patrol:
  app_name: todoapp
  flavor: development
  android:
    package_name: com.primeholding.liquidtools
  ios:
    bundle_id: com.primeholding.liquidtools
    app_name: todoapp 

    

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500

r_flutter:
  intl: lib/l10n/arb/en.arb
  intl_features:
    - name: error
    - name: field
    - name: lib_dev_menu
    - name: lib_router
