package com.primeholding.rxbloc_generator_plugin.intent_action;

import com.primeholding.rxbloc_generator_plugin.intention_action.SnippetType;
import com.primeholding.rxbloc_generator_plugin.intention_action.Snippets;
import org.junit.Test;

import static com.primeholding.rxbloc_generator_plugin.intention_action.SnippetType.*;
import static org.junit.Assert.*;

public class SnippetsTest {
    @Test
    public void testRxResultBuilder() {

        compare(RxResultBuilder, "RxResultBuilder<BlocType, StateType>(\n" +
                " state: (bloc) => bloc.states.someState, // pick a specific state you want to listen for\n" +
                " buildSuccess: (context, data, bloc) => const SizedBox(),\n" +
                " buildLoading: (context, bloc) => \n" +
                "   const CircularProgressIndicator(),\n" +
                " buildError: (context, error, bloc) => \n" +
                "   Text(error.toString()),\n" +
                ")\n");
    }

    @Test
    public void testRxPaginatedBuilder() {

        compare(RxPaginatedBuilder, "RxPaginatedBuilder<BlocType, StateType>.withRefreshIndicator(\n" +
                "          state: (bloc) => bloc.states.someState, // pick a specific state you want to listen for\n" +
                "          onBottomScrolled: (bloc) => bloc.events.loadPage(),\n" +
                "          onRefresh: (bloc) async {\n" +
                "            bloc.events.loadPage(reset: true);\n" +
                "            return bloc.states.refreshDone;\n" +
                "          },\n" +
                "          buildSuccess: (context, list, bloc) => ListView.builder(\n" +
                "            itemBuilder: (context, index) {\n" +
                "               final item = list.getItem(index);\n" +
                "\n" +
                "               if (item == null) {\n" +
                "                return const YourProgressIndicator();\n" +
                "               }\n" +
                "\n" +
                "              return YourListTile(item: item);\n" +
                "            },\n" +
                "            itemCount: list.itemCount,\n" +
                "          ),\n" +
                "          buildLoading: (context, list, bloc) =>\n" +
                "              const YourProgressIndicator(),\n" +
                "          buildError: (context, list, bloc) =>\n" +
                "              YourErrorWidget(error: list.error!),\n" +
                "        )\n");
    }

    @Test
    public void testRxBlocListener() {

        compare(RxBlocListener, "RxBlocListener<BlocType, StateType>(\n" +
                "  state: (bloc) => bloc.states.someState, // pick a specific state you want to listen for\n" +
                "  listener: (context, state) {\n" +
                "    // do stuff here based on BlocA's state\n" +
                "  }, \n" +
                "  child: const SizedBox(),\n" +
                ")\n");
    }

    @Test
    public void testRxFormFieldBuilder() {

        compare(RxFormFieldBuilder, "RxFormFieldBuilder<BlocType, StateType>(\n" +
                "     state: (bloc) => bloc.states.someState, // pick a specific state you want to listen for\n" +
                "     showErrorState: (bloc) => bloc.states.showErrors,\n" +
                "     builder: (fieldState) => Column(\n" +
                "       children: [\n" +
                "         const SizedBox(),\n" +
                "         //show errors, say for instance the user tries to save the\n" +
                "         //changes to the form, but they forgot to select a color.\n" +
                "         if (fieldState.showError)\n" +
                "           Row(\n" +
                "             children: [\n" +
                "               Text(\n" +
                "                 fieldState.error,\n" +
                "               ),\n" +
                "             ],\n" +
                "           ),\n" +
                "       ],\n" +
                "      ),\n" +
                "   )\n");
    }

    @Test
    public void testRxTextFormFieldBuilder() {
        compare(RxTextFormFieldBuilder, "RxTextFormFieldBuilder<BlocType>( \n" +
                " state: (bloc) => bloc.states.someState, // pick a specific state you want to listen for\n" +
                " showErrorState: (bloc) => bloc.states.showErrors,\n" +
                " onChanged: (bloc, value) => bloc.events.specificEvent(value), // pick a specific event the field will to send data to\n" +
                "   ///TODO: Use the controller from the fieldState\n" +
                "   /// example: `controller: fieldState.controller`\n" +
                "\n" +
                "   ///TODO: Copy the decoration generated by the builder widget, which\n" +
                "   ///contains stuff like when to show errors, with additional\n" +
                "   ///decoration\n" +
                "   ///Example `decoration: fieldState.decoration.copyWithDecoration(InputStyles.textFieldDecoration)`\n" +
                " builder: (fieldState) => const SizedBox(),)\n");
    }

    @Test
    public void testRxBlocBuilder() {

        compare(RxBlocBuilder, "RxBlocBuilder<BlocType, StateType>(\n" +
                "  state: (bloc) => bloc.states.someState, // pick a specific state you want to listen for\n" +
                "  builder: (context, snapshot, bloc) =>\n" +
                "    const SizedBox(),\n" +
                ")\n");
    }

    private void compare(SnippetType snippet, String result) {
        String replacement = Snippets.getSnippet(snippet, "const SizedBox()");
        assertEquals(result, replacement);
    }

}
