name: example
description: A sample RX bloc application
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rx_bloc: any
  rx_bloc: any
  rxdart: ^0.28.0


dev_dependencies:
  build_runner: any
  clean_coverage: ^0.0.3
  flutter_lints: any
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  rx_bloc_generator: any
  rx_bloc_test: any
  test: any

flutter:
  uses-material-design: true
