// Mocks generated by Mockito 5.0.7 from annotations
// in bloc_sample/test/feature_puppy/details/blocs/puppy_details_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:bloc/src/bloc.dart' as _i5;
import 'package:bloc/src/transition.dart' as _i4;
import 'package:bloc_sample/base/common_blocs/coordinator_bloc.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

class _FakeCoordinatorState extends _i1.Fake implements _i2.CoordinatorState {}

class _FakeStreamSubscription<T> extends _i1.Fake
    implements _i3.StreamSubscription<T> {}

/// A class which mocks [CoordinatorBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCoordinatorBloc extends _i1.Mock implements _i2.CoordinatorBloc {
  MockCoordinatorBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CoordinatorState get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakeCoordinatorState()) as _i2.CoordinatorState);
  @override
  _i3.Stream<_i2.CoordinatorState> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: Stream<_i2.CoordinatorState>.empty())
          as _i3.Stream<_i2.CoordinatorState>);
  @override
  _i3.Stream<
      _i4.Transition<_i2.CoordinatorEvent, _i2.CoordinatorState>> transformEvents(
          _i3.Stream<_i2.CoordinatorEvent>? events,
          _i5.TransitionFunction<_i2.CoordinatorEvent, _i2.CoordinatorState>?
              transitionFn) =>
      (super.noSuchMethod(
              Invocation.method(#transformEvents, [events, transitionFn]),
              returnValue:
                  Stream<_i4.Transition<_i2.CoordinatorEvent, _i2.CoordinatorState>>.empty())
          as _i3.Stream<
              _i4.Transition<_i2.CoordinatorEvent, _i2.CoordinatorState>>);
  @override
  _i3.Stream<_i2.CoordinatorState> mapEventToState(
          _i2.CoordinatorEvent? event) =>
      (super.noSuchMethod(Invocation.method(#mapEventToState, [event]),
              returnValue: Stream<_i2.CoordinatorState>.empty())
          as _i3.Stream<_i2.CoordinatorState>);
  @override
  void add(_i2.CoordinatorEvent? event) =>
      super.noSuchMethod(Invocation.method(#add, [event]),
          returnValueForMissingStub: null);
  @override
  void onEvent(_i2.CoordinatorEvent? event) =>
      super.noSuchMethod(Invocation.method(#onEvent, [event]),
          returnValueForMissingStub: null);
  @override
  void emit(_i2.CoordinatorState? state) =>
      super.noSuchMethod(Invocation.method(#emit, [state]),
          returnValueForMissingStub: null);
  @override
  void onTransition(
          _i4.Transition<_i2.CoordinatorEvent, _i2.CoordinatorState>?
              transition) =>
      super.noSuchMethod(Invocation.method(#onTransition, [transition]),
          returnValueForMissingStub: null);
  @override
  _i3.Stream<
      _i4.Transition<_i2.CoordinatorEvent, _i2.CoordinatorState>> transformTransitions(
          _i3.Stream<_i4.Transition<_i2.CoordinatorEvent, _i2.CoordinatorState>>?
              transitions) =>
      (super.noSuchMethod(
              Invocation.method(#transformTransitions, [transitions]),
              returnValue:
                  Stream<_i4.Transition<_i2.CoordinatorEvent, _i2.CoordinatorState>>.empty())
          as _i3.Stream<
              _i4.Transition<_i2.CoordinatorEvent, _i2.CoordinatorState>>);
  @override
  _i3.Future<void> close() => (super.noSuchMethod(Invocation.method(#close, []),
      returnValue: Future<void>.value(null),
      returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  _i3.StreamSubscription<_i2.CoordinatorState> listen(
          void Function(_i2.CoordinatorState)? onData,
          {Function? onError,
          void Function()? onDone,
          bool? cancelOnError}) =>
      (super.noSuchMethod(
              Invocation.method(#listen, [
                onData
              ], {
                #onError: onError,
                #onDone: onDone,
                #cancelOnError: cancelOnError
              }),
              returnValue: _FakeStreamSubscription<_i2.CoordinatorState>())
          as _i3.StreamSubscription<_i2.CoordinatorState>);
  @override
  void onChange(_i4.Change<_i2.CoordinatorState>? change) =>
      super.noSuchMethod(Invocation.method(#onChange, [change]),
          returnValueForMissingStub: null);
  @override
  void addError(Object? error, [StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#addError, [error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void onError(Object? error, StackTrace? stackTrace) =>
      super.noSuchMethod(Invocation.method(#onError, [error, stackTrace]),
          returnValueForMissingStub: null);
}
