name: booking_app
description: A new Flutter project.
homepage: https://primeholding.com
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  collection: ^1.18.0
  cupertino_icons: ^1.0.5
  dio: ^5.3.0
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.1+2
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: any
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.2
  golden_toolkit: ^0.15.0
  http: ^1.1.0 # This package is used for the local server (if not used, can be removed)
  jaguar_jwt: ^3.0.0 # This package is used for the local server (if not used, can be removed)
  json_annotation: ^4.7.0
  jwt_decoder: ^2.0.1
  provider: ^6.0.3
  retrofit: ^4.0.1
  rx_bloc: any
  rx_bloc_list: any
  rxdart: ^0.28.0
  shared_preferences: ^2.0.15

  # Server related packages
  shelf: ^1.4.1
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.11
  # flutter_driver:
  #   sdk: flutter
  flutter_lints: any
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.0
  json_serializable: ^6.5.1
  mockito: ^5.3.2
  r_flutter: 0.9.0
  retrofit_generator: ^8.1.2
  rx_bloc_generator: any
  rx_bloc_test: any
  test: any

flutter:
  uses-material-design: true
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500

r_flutter:
  intl: lib/l10n/arb/en.arb
  intl_features:
    - name: deep_link_flow
    - name: error
    - name: feature_counter
    - name: feature_login
    - name: feature_notifications
    - name: feature_enter_message
    - name: field