name: rx_bloc_favorites_advanced
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_stream_list_nullsafety:
  appbar_textfield:
  badges: ^3.1.2
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.1
  favorites_advanced_base:
    path: ../favorites_advanced_base
  flow_builder: ^0.1.0
  flutter:
    sdk: flutter
  flutter_rx_bloc: any
  image_picker: ^1.0.4
  provider: ^6.1.1
  rx_bloc: any
  rx_bloc_list: any
  rxdart: ^0.28.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  test: 1.15.2
  build_runner: ^2.4.11
  clean_coverage: ^0.0.3
  flutter_lints: any
#  flutter_gherkin: ^1.1.9
  mockito: ^5.4.2
  quiver: ^3.0.1+1
  rx_bloc_generator: any
  rx_bloc_test: any
  test: ^1.24.3

flutter:
  uses-material-design: true

  assets:
     - assets/
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700