name: rx_bloc_favorites_advanced
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_stream_list_nullsafety:
  appbar_textfield:
  badges: ^3.1.2
  collection: ^1.17.1
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.1
  favorites_advanced_base:
    path: ../favorites_advanced_base
  flow_builder: ^0.0.10
  flutter:
    sdk: flutter
  flutter_rx_bloc: ^6.0.0
  image_picker: ^1.0.4
  provider: ^6.1.1
  rx_bloc: ^5.1.0
  rx_bloc_list: ^4.1.0
  rxdart: ^0.27.7

dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  test: 1.15.2
  build_runner: ^2.4.6
  clean_coverage: ^0.0.3
  flutter_lints: any
#  flutter_gherkin: ^1.1.9
  mockito: ^5.4.2
  quiver: ^3.0.1+1
  rx_bloc_generator: ^7.1.0
  rx_bloc_test: ^4.1.0
  test: ^1.24.3

dependency_overrides:
  appbar_textfield:
    git:
      url: https://github.com/zdravkoc/appbar_textfield.git
      ref: master
  favorites_advanced_base:
    path: ../favorites_advanced_base
  flutter_rx_bloc:
    path: ../../../packages/flutter_rx_bloc
  rx_bloc:
    path: ../../../packages/rx_bloc
  rx_bloc_generator:
    path: ../../../packages/rx_bloc_generator
  rx_bloc_list:
    path: ../../../packages/rx_bloc_list
  rx_bloc_test:
    path: ../../../packages/rx_bloc_test

flutter:
  uses-material-design: true

  assets:
     - assets/
  #  - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700