{{> licence.dart }}

import 'package:flutter/material.dart';
// Material Design System: https://m2.material.io/design/color/the-color-system.html

@immutable
class DesignSystemColors {
  const DesignSystemColors.light()
    : brightness = Brightness.light,
      colorScheme = const ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xFF1E3A5F),
        surfaceTint: Color(0xFF1E3A5F),
        onPrimary: Color(0xFFFFFFFF),
        primaryContainer: Color(0xFFD6E3F5),
        onPrimaryContainer: Color(0xFF0A1929),
        secondary: Color(0xFF0D7377),
        onSecondary: Color(0xFFFFFFFF),
        secondaryContainer: Color(0xFFB8E4E6),
        onSecondaryContainer: Color(0xFF052E30),
        tertiary: Color(0xFF5C6B7A),
        onTertiary: Color(0xFFFFFFFF),
        tertiaryContainer: Color(0xFFE0E7EC),
        onTertiaryContainer: Color(0xFF19242D),
        error: Color(0xFFBA1A1A),
        onError: Color(0xFFFFFFFF),
        errorContainer: Color(0xFFFFDAD6),
        onErrorContainer: Color(0xFF410002),
        surface: Color(0xFFF8F9FA),
        onSurface: Color(0xFF1A1D21),
        onSurfaceVariant: Color(0xFF43474E),
        outline: Color(0xFF74787D),
        outlineVariant: Color(0xFFC4C6CA),
        shadow: Color(0xFF000000),
        scrim: Color(0xFF000000),
        inverseSurface: Color(0xFF2F3033),
        inversePrimary: Color(0xFFABC7F8),
        primaryFixed: Color(0xFFD6E3F5),
        onPrimaryFixed: Color(0xFF0A1929),
        primaryFixedDim: Color(0xFFABC7F8),
        onPrimaryFixedVariant: Color(0xFF05254A),
        secondaryFixed: Color(0xFFB8E4E6),
        onSecondaryFixed: Color(0xFF052E30),
        secondaryFixedDim: Color(0xFF9CC8CA),
        onSecondaryFixedVariant: Color(0xFF0D5C5F),
        tertiaryFixed: Color(0xFFE0E7EC),
        onTertiaryFixed: Color(0xFF19242D),
        tertiaryFixedDim: Color(0xFFC4CBD2),
        onTertiaryFixedVariant: Color(0xFF445360),
        surfaceDim: Color(0xFFD8D9DC),
        surfaceBright: Color(0xFFF8F9FA),
        surfaceContainerLowest: Color(0xFFFFFFFF),
        surfaceContainerLow: Color(0xFFF2F2F5),
        surfaceContainer: Color(0xFFECEDF0),
        surfaceContainerHigh: Color(0xFFE6E7EA),
        surfaceContainerHighest: Color(0xFFE0E1E4),
      ),
      appleBackground = const Color(0xFF000000),
      googleBackground = const Color(0xFFFFFFFF),
      facebookBackground = const Color(0xFF1877F2);

  const DesignSystemColors.dark()
    : brightness = Brightness.dark,
      colorScheme = const ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xFFABC7F8),
        surfaceTint: Color(0xFFABC7F8),
        onPrimary: Color(0xFF0A1929),
        primaryContainer: Color(0xFF05254A),
        onPrimaryContainer: Color(0xFFD6E3F5),
        secondary: Color(0xFF9CC8CA),
        onSecondary: Color(0xFF052E30),
        secondaryContainer: Color(0xFF0D5C5F),
        onSecondaryContainer: Color(0xFFB8E4E6),
        tertiary: Color(0xFFC4CBD2),
        onTertiary: Color(0xFF19242D),
        tertiaryContainer: Color(0xFF445360),
        onTertiaryContainer: Color(0xFFE0E7EC),
        error: Color(0xFFFFB4AB),
        onError: Color(0xFF690005),
        errorContainer: Color(0xFF93000A),
        onErrorContainer: Color(0xFFFFDAD6),
        surface: Color(0xFF1A1D21),
        onSurface: Color(0xFFE0E1E4),
        onSurfaceVariant: Color(0xFFC4C6CA),
        outline: Color(0xFF8E9094),
        outlineVariant: Color(0xFF43474E),
        shadow: Color(0xFF000000),
        scrim: Color(0xFF000000),
        inverseSurface: Color(0xFFE0E1E4),
        inversePrimary: Color(0xFF1E3A5F),
        primaryFixed: Color(0xFFD6E3F5),
        onPrimaryFixed: Color(0xFF0A1929),
        primaryFixedDim: Color(0xFFABC7F8),
        onPrimaryFixedVariant: Color(0xFF05254A),
        secondaryFixed: Color(0xFFB8E4E6),
        onSecondaryFixed: Color(0xFF052E30),
        secondaryFixedDim: Color(0xFF9CC8CA),
        onSecondaryFixedVariant: Color(0xFF0D5C5F),
        tertiaryFixed: Color(0xFFE0E7EC),
        onTertiaryFixed: Color(0xFF19242D),
        tertiaryFixedDim: Color(0xFFC4CBD2),
        onTertiaryFixedVariant: Color(0xFF445360),
        surfaceDim: Color(0xFF1A1D21),
        surfaceBright: Color(0xFF3F4246),
        surfaceContainerLowest: Color(0xFF15181B),
        surfaceContainerLow: Color(0xFF1A1D21),
        surfaceContainer: Color(0xFF1E2125),
        surfaceContainerHigh: Color(0xFF282B2F),
        surfaceContainerHighest: Color(0xFF33363A),
      ),
      appleBackground = const Color(0xFFFFFFFF),
      googleBackground = const Color(0xFF1A1D21),
      facebookBackground = const Color(0xFF1877F2);

  final Brightness brightness;
  final ColorScheme colorScheme;
  final Color appleBackground;
  final Color googleBackground;
  final Color facebookBackground;
}
