targets:
  $default:
    builders:
      rx_block:
        enabled: true
        generate_for:
          exclude:
            - test
            - example

builders:
  rx_block  :
    import: "package:rx_bloc_generator/builder.dart"
    builder_factories:
      - "buildRxBuilder"
      - "buildRxCoordinatorBuilder"
    build_extensions: {'.dart': ['rxb.g.dart']}
    auto_apply: root_package
    build_to: source
    applies_builders: ["mockito|mockBuilder"]