name: reminders
description: A new Flutter project.
homepage: https://example.com
version: 1.0.0+10

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.0.4
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  dio: ^5.3.0
  firebase_analytics: ^10.0.4
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_rx_bloc: null
  flutter_secure_storage: ^8.0.0
  flutter_slidable: ^3.0.0
  flutter_sticky_header: ^0.6.0
  go_router: ^10.0.0
  golden_toolkit: ^0.15.0
  grouped_list: ^5.1.2
  intl: ^0.19.0
  jaguar_jwt: ^3.0.0
  json_annotation: ^4.9.0
  provider: ^6.0.1
  retrofit: ^4.1.0
  rx_bloc: null
  rx_bloc_list: ^4.0.0
  rxdart: ^0.27.3
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.0.11
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: any
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.2.3
  json_serializable: ^6.8.0
  mockito: ^5.0.16
  retrofit_generator: ^8.1.1
  rx_bloc_generator: ^7.2.2
  rx_bloc_test: any
  test: any

dependency_overrides:
  flutter_rx_bloc:
    path: ../../packages/flutter_rx_bloc
  rx_bloc:
    path: ../../packages/rx_bloc
  rx_bloc_generator:
    path: ../../packages/rx_bloc_generator
  rx_bloc_list:
    path: ../../packages/rx_bloc_list
  rx_bloc_test:
    path: ../../packages/rx_bloc_test

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans/WorkSans-Medium.ttf
          weight: 500
