name: "Build and Test rx_bloc packages"

on:
  push:
    paths:
      - ".github/workflows/build_and_test_rx_bloc_packages.yaml"
      - "packages/**"
      - "examples/**"
     
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
      - "packages/**"
      - "examples/**"    

jobs:
  examples:
    strategy:
      matrix:
        folder:
          [
            "examples/booking_app",
            "examples/counter",
            "examples/division",
            "examples/favorites_advanced/rx_bloc_favorites_advanced",
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version 
      - name: Install Dependencies
        working-directory: ${{ matrix.folder }}
        run: flutter pub get
      - name: Analyze
        working-directory: ${{ matrix.folder }}
        run: flutter analyze lib
      - name: Run tests
        working-directory: ${{ matrix.folder }}
        run: |
          if [ -d "test" ]; then
            flutter test --coverage --exclude-tags=not-tests
          fi
      - name: Remove unnecessary files
        working-directory: ${{ matrix.folder }}
        run: flutter pub run clean_coverage clean --exclusions '**/.g.dart','**repository.dart','**rxb.g.dart' coverage/lcov.info
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "${{ matrix.folder }}/coverage/lcov.info"
          min_coverage: 50
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ matrix.folder }}/coverage
  flutter_packages:
    strategy:
      matrix:
        folder:
          [
            "packages/rx_bloc_list",
            "packages/flutter_rx_bloc",
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version 
      - name: Install Dependencies
        working-directory: ${{ matrix.folder }}
        run: flutter pub get
      - name: Analyze
        working-directory: ${{ matrix.folder }}
        run: flutter analyze lib
      - name: Verify package for publishing
        working-directory: ${{ matrix.folder }}
        run: dart pub publish --dry-run
      - name: Run tests
        working-directory: ${{ matrix.folder }}
        run: |
          if [ -d "test" ]; then
            flutter test --coverage --exclude-tags=not-tests
          fi
      - name: Remove unnecessary files
        working-directory: ${{ matrix.folder }}
        run: flutter pub run clean_coverage clean --exclusions '**/.g.dart','**repository.dart','**rxb.g.dart' coverage/lcov.info
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "${{ matrix.folder }}/coverage/lcov.info"
          min_coverage: 89
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ matrix.folder }}/coverage
  packages:
    strategy:
      matrix:
        folder:
          [
            "packages/rx_bloc",
            "packages/rx_bloc_test",
            "packages/rx_bloc_generator",
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version 
      - name: Install Dependencies
        working-directory: ${{ matrix.folder }}
        run: dart pub get
      - name: Analyze
        working-directory: ${{ matrix.folder }}
        run: flutter analyze lib
      - name: Verify package for publishing
        working-directory: ${{ matrix.folder }}
        run: dart pub publish --dry-run
      - name: Run tests
        working-directory: ${{ matrix.folder }}
        run: |
          if [ -d "test" ]; then
            dart test --coverage=coverage --exclude-tags=not-tests
          fi
      - name: Format coverage
        working-directory: ${{ matrix.folder }}
        run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib
      - name: Remove unnecessary files
        working-directory: ${{ matrix.folder }}
        run: dart run clean_coverage clean --exclusions '**/.g.dart','**repository.dart','**rxb.g.dart' coverage/lcov.info
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "${{ matrix.folder }}/coverage/lcov.info"
          min_coverage: 67
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ matrix.folder }}/coverage
  cli_packages:
    strategy:
      matrix:
        folder:
          [
            "packages/rx_bloc_cli",
          ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version 
      - name: Install Dependencies
        working-directory: ${{ matrix.folder }}
        run: dart pub get
      - name: Compile Bundles
        working-directory: ${{ matrix.folder }}
        run: bash bin/compile_bundles.sh
      - name: Analyze
        working-directory: ${{ matrix.folder }}
        run: flutter analyze lib
      - name: Run tests
        working-directory: ${{ matrix.folder }}
        run: |
          if [ -d "test" ]; then
            dart test --coverage=coverage --exclude-tags=not-tests
          fi
      - name: Format coverage
        working-directory: ${{ matrix.folder }}
        run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib
      - name: Remove unnecessary files
        working-directory: ${{ matrix.folder }}
        run: dart run clean_coverage clean --exclusions '**/.g.dart','**repository.dart','**rxb.g.dart' coverage/lcov.info
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v2
        with:
          path: "${{ matrix.folder }}/coverage/lcov.info"
          min_coverage: 67
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ${{ matrix.folder }}/coverage
          
  build:
    needs: [examples, packages, flutter_packages, cli_packages]
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'
