name: "Build and deploy Android App"

# Define events when this workflow is triggered
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/deploy_android_app.yaml"
      - "examples/booking_app"
      
  pull_request:
    paths:
      - ".github/workflows/deploy_android_app.yaml"
      - "examples/booking_app"

# Define local variables 
env:
  PROJECT_PATH : "examples/booking_app"

jobs:
  deploy_android_app:
    defaults:
      run:
        working-directory: ${{ env.PROJECT_PATH }}
    runs-on: ubuntu-latest
    #needs: test_app_with_coverage
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: flutter-:os:-:channel:-:version:-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}
      - run: dart --version
      - run: flutter --version
      - name: Configure build
        run: |
          echo "${{ secrets.STORE_FILE_CONTENT_BASE64 }}" | base64 --decode > android/key.jks
          echo "${{ secrets.KEY_PROPERTIES_CONTENT_BASE64 }}" | base64 --decode > android/key.properties
      - name: Install Dependencies
        run: |
          flutter clean
          flutter pub get
      - name: Build android app
        run: flutter build appbundle --release -t lib/main.dart
      - name: Prepare artifacts for publishing
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: "${{ env.PROJECT_PATH }}/build/app/outputs/bundle/release/app-release.aab"
      - name: Release app to internal track
        if: false
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}
          packageName: com.primeholding.booking_app
          releaseFiles: "${{ env.PROJECT_PATH }}/build/app/outputs/bundle/release/app-release.aab"
          track: internal
          status: completed
