name: "Test and deploy Booking app"

# Define events when this workflow is triggered
on:
  push:
    paths:
      - ".github/workflows/test_and_deploy_booking_app.yaml"
      - ".github/workflows/test_app_with_coverage.yaml"
      - ".github/workflows/deploy_android_app.yaml"
      - ".github/workflows/deploy_ios_app.yaml"
      - "examples/booking_app"
      
  pull_request:
    paths:
      - ".github/workflows/test_and_deploy_booking_app.yaml"
      - ".github/workflows/test_app_with_coverage.yaml"
      - ".github/workflows/deploy_android_app.yaml"
      - ".github/workflows/deploy_ios_app.yaml"
      - "examples/booking_app"

# Define jobs that should be running within this workflow
jobs:
  test_booking_app:
    uses: ./.github/workflows/test_app_with_coverage.yaml
    with:
      project_path: "examples/booking_app"
      min_coverage: 55
      flutter_version: '3.7.12'
      
  deploy_android_booking_app:
    needs: [test_booking_app]
    uses: ./.github/workflows/deploy_android_app.yaml
    with:
      project_path: "examples/booking_app"
      package_name: com.primeholding.booking_app
      publish_to_store: false
      flutter_version: '3.7.12'
    secrets:
      key_properties_content_base64: ${{ secrets.KEY_PROPERTIES_CONTENT_BASE64 }}
      store_file_content_base64: ${{ secrets.STORE_FILE_CONTENT_BASE64 }}
      playstore_account_key: ${{ secrets.PLAYSTORE_ACCOUNT_KEY }}

  deploy_ios_booking_app:
    needs: [test_booking_app]
    uses: ./.github/workflows/deploy_ios_app.yaml
    with:
      project_path: "examples/booking_app"
      flutter_version: '3.7.12'
    secrets:
      appstore_issuer_id: ${{ secrets.APPSTORE_ISSUER_ID }}
      appstore_cert_base64: ${{ secrets.APPSTORE_CERT_BASE64 }}
      appstore_cert_password: ${{ secrets.APPSTORE_CERT_PASSWORD }}
      mobile_provision_base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
      keychain_password: ${{ secrets.KEYCHAIN_PASSWORD }}
      appstore_api_key_id: ${{ secrets.APPSTORE_API_KEY_ID }}
      appstore_api_key_base64: ${{ secrets.APPSTORE_API_KEY_BASE64 }}
        
