# This workflow uses actions that are not certified by GitHub
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Test IntelliJ RxBloC Plugin

on:
  push:
    paths:
      - "extensions/intellij/intellij_generator_plugin/**"
      - ".github/workflows/test_rx_bloc_intellij_plugin.yml"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.10.2'
        build-root-directory: extensions/intellij/intellij_generator_plugin

    - name: Build with Gradle
      run: |
        cd extensions/intellij/intellij_generator_plugin
        ./gradlew test