import 'package:favorites_advanced_base/core.dart';

class StubDataSource {
  static const _description = '''
 is situated on a 9 km stretch of private beach on Saadiyat Island. This hotel offers air-conditioned rooms with a balcony. It has a health club with an outdoor pool.
A spacious seating area with a 42-inch flat-screen TV and an iPod docking station are in Hyatt Abu Dhabi’s modern rooms. Each has floor-to-ceiling windows and is decorated in soft colours. An open-plan bathroom with an oversized bathtub and a separate rain-shower is included.
Relaxing massages and various beauty treatments are available at Atarmia Spa. It includes a gym and private treatment rooms for men and women.
Park Hyatt Abu Dhabi Hotel and Villas has 3 in-house restaurants.
Each offers a wide selection of international cuisine. The Beach House Restaurant features panoramic views of Saadiyat Beach and the landscaped hotel gardens.
Abu Dhabi International Airport is 35 minutes’ drive away. Park Hyatt Abu Dhabi provides free parking on site.
Couples particularly like the location — they rated it 9.3 for a two-person trip.
We speak your language!
''';

  static final _features = [
    'Free WiFi',
    'Beachfront',
    'Free parking',
    'Family rooms',
    'Bar',
  ];

  static final hotelsDB = [
    Hotel(
      id: '1',
      title: 'Premier Inn Dubai International Airport',
      imagePath: 'assets/hotel_0.png',
      perNight: 100,
      isFavorite: false,
      roomCapacity: 2,
      personCapacity: 4,
      startWorkDate: _getDateForMonthAndDay(1, 1),
      endWorkDate: _getDateForMonthAndDay(2, 1),
    ),
    Hotel(
      id: '2',
      title: 'Avani Deira Dubai Hotel',
      imagePath: 'assets/hotel_1.png',
      perNight: 170,
      isFavorite: false,
      roomCapacity: 1,
      personCapacity: 2,
      startWorkDate: _getDateForMonthAndDay(2, 1),
      endWorkDate: _getDateForMonthAndDay(3, 1),
    ),
    Hotel(
      id: '3',
      title: 'Swissotel Al Ghurair',
      imagePath: 'assets/hotel_2.png',
      perNight: 135,
      isFavorite: false,
      roomCapacity: 1,
      personCapacity: 1,
      startWorkDate: _getDateForMonthAndDay(3, 1),
      endWorkDate: _getDateForMonthAndDay(4, 1),
    ),
    Hotel(
      id: '4',
      title: 'Hyatt Place Dubai Jumeirah Residences',
      imagePath: 'assets/hotel_3.png',
      perNight: 200,
      isFavorite: false,
      roomCapacity: 2,
      personCapacity: 4,
      startWorkDate: _getDateForMonthAndDay(4, 1),
      endWorkDate: _getDateForMonthAndDay(6, 1),
    ),
    Hotel(
      id: '5',
      title: 'Ramee Rose Hotel',
      imagePath: 'assets/hotel_4.png',
      perNight: 150,
      isFavorite: false,
      roomCapacity: 3,
      personCapacity: 5,
      startWorkDate: _getDateForMonthAndDay(5, 1),
      endWorkDate: _getDateForMonthAndDay(6, 1),
    ),
    Hotel(
      id: '6',
      title: 'Atana Hotel',
      imagePath: 'assets/hotel_5.png',
      perNight: 220,
      isFavorite: false,
      roomCapacity: 3,
      personCapacity: 6,
      startWorkDate: _getDateForMonthAndDay(6, 1),
      endWorkDate: _getDateForMonthAndDay(7, 1),
    ),
    Hotel(
      id: '7',
      title: 'Rove Healthcare City',
      imagePath: 'assets/hotel_6.png',
      perNight: 140,
      isFavorite: false,
      roomCapacity: 1,
      personCapacity: 1,
      startWorkDate: _getDateForMonthAndDay(7, 1),
      endWorkDate: _getDateForMonthAndDay(8, 1),
    ),
    Hotel(
      id: '8',
      title: 'Rove Healthcare',
      imagePath: 'assets/hotel_7.png',
      perNight: 85,
      isFavorite: false,
      roomCapacity: 3,
      personCapacity: 3,
      startWorkDate: _getDateForMonthAndDay(8, 1),
      endWorkDate: _getDateForMonthAndDay(9, 1),
    ),
    Hotel(
      id: '9',
      title: 'Millennium Airport Hotel Dubai',
      imagePath: 'assets/hotel_8.png',
      perNight: 65,
      isFavorite: false,
      roomCapacity: 2,
      personCapacity: 3,
      startWorkDate: _getDateForMonthAndDay(9, 1),
      endWorkDate: _getDateForMonthAndDay(10, 1),
    ),
    Hotel(
      id: '10',
      title: 'Millennium Airport',
      imagePath: 'assets/hotel_9.png',
      perNight: 100,
      isFavorite: false,
      roomCapacity: 4,
      personCapacity: 4,
      startWorkDate: _getDateForMonthAndDay(10, 1),
      endWorkDate: _getDateForMonthAndDay(11, 1),
    ),
    Hotel(
      id: '11',
      title: 'Millennium Airport Hotel Dubai',
      imagePath: 'assets/hotel_10.png',
      perNight: 120,
      isFavorite: false,
      roomCapacity: 4,
      personCapacity: 8,
      startWorkDate: _getDateForMonthAndDay(11, 1),
      endWorkDate: _getDateForMonthAndDay(12, 1),
    ),
    Hotel(
      id: '12',
      title: 'Millennium Airport Hotel Dubai',
      imagePath: 'assets/hotel_11.png',
      perNight: 70,
      isFavorite: false,
      roomCapacity: 4,
      personCapacity: 6,
      startWorkDate: _getDateForMonthAndDay(12, 1),
      endWorkDate: _getDateForMonthAndDay(1, 1, true),
    ),
    Hotel(
      id: '13',
      title: 'Millennium Airport Hotel Dubai',
      imagePath: 'assets/hotel_12.png',
      perNight: 220,
      isFavorite: false,
      roomCapacity: 4,
      personCapacity: 7,
      startWorkDate: _getDateForMonthAndDay(1, 10),
      endWorkDate: _getDateForMonthAndDay(3, 25),
    ),
    Hotel(
      id: '14',
      title: 'Taj Dubai',
      imagePath: 'assets/hotel_13.png',
      perNight: 80,
      isFavorite: false,
      roomCapacity: 2,
      personCapacity: 4,
      startWorkDate: _getDateForMonthAndDay(3, 26),
      endWorkDate: _getDateForMonthAndDay(5, 30),
    ),
    Hotel(
      id: '15',
      title: 'Rove Downtown Dubai',
      imagePath: 'assets/hotel_14.png',
      perNight: 110,
      isFavorite: false,
      roomCapacity: 1,
      personCapacity: 2,
      startWorkDate: _getDateForMonthAndDay(5, 31),
      endWorkDate: _getDateForMonthAndDay(7, 10),
    ),
    Hotel(
      id: '16',
      title: 'Premier Inn Dubai Al Jaddaf',
      imagePath: 'assets/hotel_15.png',
      perNight: 99,
      isFavorite: false,
      roomCapacity: 2,
      personCapacity: 3,
      startWorkDate: _getDateForMonthAndDay(7, 11),
      endWorkDate: _getDateForMonthAndDay(9, 6),
    ),
    Hotel(
      id: '17',
      title: 'Hyatt Place Dubai Al Rigga Residences',
      imagePath: 'assets/hotel_16.png',
      perNight: 120,
      isFavorite: false,
      roomCapacity: 3,
      personCapacity: 5,
      startWorkDate: _getDateForMonthAndDay(9, 7),
      endWorkDate: _getDateForMonthAndDay(11, 15),
    ),
    Hotel(
      id: '18',
      title: '5 Stars',
      imagePath: 'assets/hotel_17.png',
      perNight: 150,
      isFavorite: false,
      roomCapacity: 3,
      personCapacity: 3,
      startWorkDate: _getDateForMonthAndDay(11, 16),
      endWorkDate: _getDateForMonthAndDay(1, 9, true),
    ),
    Hotel(
      id: '19',
      title: 'Hyatt Place Dubai Al Rigga Residences',
      imagePath: 'assets/hotel_18.png',
      perNight: 79,
      isFavorite: false,
      roomCapacity: 4,
      personCapacity: 4,
      startWorkDate: _getDateForMonthAndDay(1, 1),
      endWorkDate: _getDateForMonthAndDay(6, 30),
    ),
    Hotel(
      id: '20',
      title: 'Regal Plaza Hotel',
      imagePath: 'assets/hotel_19.png',
      perNight: 200,
      isFavorite: false,
      roomCapacity: 1,
      personCapacity: 1,
      startWorkDate: _getDateForMonthAndDay(7, 1),
      endWorkDate: _getDateForMonthAndDay(12, 31),
    ),
  ];

  static final hotelsExtraDetailsDB = [
    HotelExtraDetails(
      id: '1',
      hotelId: ['1'],
      subTitle: '4 Stars',
      dist: 120,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '2',
      hotelId: ['2'],
      subTitle: '5 Stars',
      dist: 62,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '3',
      hotelId: ['3'],
      subTitle: '3 Stars',
      dist: 320,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '4',
      hotelId: ['4'],
      subTitle: '6 Stars',
      dist: 280,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '5',
      hotelId: ['5'],
      subTitle: '5 Stars',
      dist: 125,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '6',
      hotelId: ['6'],
      subTitle: '5 Stars',
      dist: 172,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '7',
      hotelId: ['7'],
      subTitle: '6 Stars',
      dist: 88,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '8',
      hotelId: ['8'],
      subTitle: '5 Stars',
      dist: 165,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '9',
      hotelId: ['9'],
      subTitle: '4 Stars',
      dist: 150,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '10',
      hotelId: ['10'],
      subTitle: '6 Stars',
      dist: 98,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '11',
      hotelId: ['11'],
      subTitle: '5 Stars',
      dist: 83,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '12',
      hotelId: ['12'],
      subTitle: '5 Stars',
      dist: 137,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '13',
      hotelId: ['13'],
      subTitle: '5 Stars',
      dist: 178,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '14',
      hotelId: ['14'],
      subTitle: '6 Stars',
      dist: 283,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '15',
      hotelId: ['15'],
      subTitle: '5 Stars',
      dist: 313,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '16',
      hotelId: ['16'],
      subTitle: '5 Stars',
      dist: 295,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '17',
      hotelId: ['17'],
      subTitle: '5 Stars',
      dist: 104,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '18',
      hotelId: ['18'],
      subTitle: 'Subtitle',
      dist: 192,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '19',
      hotelId: ['19'],
      subTitle: '5 Stars',
      dist: 380,
      rating: 4.3,
      reviews: 34,
    ),
    HotelExtraDetails(
      id: '20',
      hotelId: ['20'],
      subTitle: '6 Stars',
      dist: 123,
      rating: 4.3,
      reviews: 34,
    ),
  ];

  static final hotelsFullExtraDetailsDB = [
    HotelFullExtraDetails(
      id: '1',
      hotelId: ['1'],
      description: _description,
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '2',
      hotelId: ['2'],
      description: 'Avani Deira Dubai Hotel $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '3',
      hotelId: ['3'],
      description: 'Swissotel Al Ghurair $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '4',
      hotelId: ['4'],
      description: 'Hyatt Place Dubai Jumeirah Residences $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '5',
      hotelId: ['5'],
      description: 'Ramee Rose Hotel $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '6',
      hotelId: ['6'],
      description: 'Atana Hotel $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '7',
      hotelId: ['7'],
      description: 'Rove Healthcare City $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '8',
      hotelId: ['8'],
      description: 'Rove Healthcare $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '9',
      hotelId: ['9'],
      description: 'Millennium Airport Hotel Dubai $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '10',
      hotelId: ['10'],
      description: 'Millennium Airport $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '11',
      hotelId: ['11'],
      description: 'Millennium Airport Hotel Dubai $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '12',
      hotelId: ['12'],
      description: 'Millennium Airport Hotel Dubai $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '13',
      hotelId: ['13'],
      description: 'Millennium Airport Hotel Dubai $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '14',
      hotelId: ['14'],
      description: 'Taj Dubai $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '15',
      hotelId: ['15'],
      description: 'Rove Downtown Dubai $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '16',
      hotelId: ['16'],
      description: 'Premier Inn Dubai Al Jaddaf $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '17',
      hotelId: ['17'],
      description: 'Hyatt Place Dubai Al Rigga Residences $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '18',
      hotelId: ['18'],
      description: 'Hyatt Place Dubai Al Rigga Residences $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '19',
      hotelId: ['19'],
      description: 'Hyatt Place Dubai Al Rigga Residences $_description',
      features: _features,
    ),
    HotelFullExtraDetails(
      id: '20',
      hotelId: ['20'],
      description: 'Regal Plaza Hotel $_description',
      features: _features,
    ),
  ];

  static DateTime _getDateForMonthAndDay(int month, int day,
          [bool isNextYear = false]) =>
      DateTime(DateTime.now().year + (isNextYear ? 1 : 0), month, day);
}
